server:
  port: 80
spring:
  application:
    name: demo
  datasource:
    ## test1 database
    test1:
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:zwsj
      username: user_frame2
      password: user_frame2
      driverClassName: oracle.jdbc.OracleDriver
    test2:
      jdbc-url: jdbc:mysql://localhost:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
#mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.gbicc.demo.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml